version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "55000:27017"

  logs-backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    container_name: "backend"
    ports:
      - "62000:3000"
    depends_on:
      - mongodb
