version: "3.8"
services:
  mongodb:
    volumes:
      - database-logs-dev:/data/db
    env_file:
      - ./env/mongo.env

  elasticsearch:
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logs-backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/service.env
    command: npm run dev

volumes:
  database-logs-dev:
  elasticsearch-data-volume:
