version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "55000:27017"

  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: "elasticsearch"
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELK_AUTH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.13.2
    container_name: "kibana"
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=${ELK_HOST}
      - ELASTICSEARCH_USERNAME=${ELK_AUTH_USER}
      - ELASTICSEARCH_PASSWORD=${ELK_AUTH_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logs-backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    container_name: "backend"
    ports:
      - "62000:3000"
    depends_on:
      - mongodb
      - elasticsearch
      - kibana
